import * as fs from 'node:fs'
import * as path from 'node:path'
import * as crypto from 'node:crypto'
import * as p from '@clack/prompts'
import chalk from 'chalk'

const CONFIG_FILE = 'watchdeck.config.js'
const ENV_FILE = '.env'

interface InitOptions {
  force: boolean
  defaults: boolean
}

function generateEncryptionKey(): string {
  return crypto.randomBytes(32).toString('hex').slice(0, 32)
}

function renderTemplate(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => vars[key] ?? '')
}

function checkExistingFiles(): { config: boolean; env: boolean } {
  return {
    config: fs.existsSync(path.resolve(process.cwd(), CONFIG_FILE)),
    env: fs.existsSync(path.resolve(process.cwd(), ENV_FILE)),
  }
}

// Inlined so tsup bundles them — no runtime file reads from disk
const CONFIG_TEMPLATE = `export default {
  port: {{PORT}},
  apiBasePath: '/api/mx',
  dashboardRoute: '/dashboard',
  dashboardMode: '{{DASHBOARD_MODE}}',

  modules: {
    discord: {{DISCORD}},
    slack: {{SLACK}},
    sslChecks: true,
    portChecks: true,
    bodyValidation: true,
  },

  defaults: {
    checkInterval: 60,
    timeout: 10000,
    expectedStatusCodes: [200],
    latencyThreshold: 5000,
    sslWarningDays: 14,
    failureThreshold: 3,
    alertCooldown: 900,
    recoveryAlert: true,
    escalationDelay: 1800,
  },

  retention: {
    detailedDays: 30,
    hourlyDays: 90,
    daily: '1year',
    notificationLogDays: 60,
  },

  rateLimits: {
    minCheckInterval: 30,
    maxConcurrentChecks: 10,
    perHostMinGap: 2,
    dbReconnectAttempts: 30,
    dbPoolSize: 10,
    maxEventListeners: 25,
  },

  buffer: {
    memoryCapacity: 1000,
  },

  sse: {
    heartbeatInterval: 30,
  },

  eventHistorySize: 100,

  aggregation: {
    time: '03:00',
  },

  cors: {
    origin: '*',
    credentials: true,
  },

  authMiddleware: null,
}
`

const ENV_TEMPLATE = `# WatchDeck Environment Variables
# Generated by: watchdeck init

# MongoDB connection string (required)
MX_DB_URI={{DB_URI}}

# MongoDB collection prefix (default: mx_)
MX_DB_PREFIX={{DB_PREFIX}}

# Discord bot token (required if modules.discord = true)
# MX_DISCORD_TOKEN=

# Slack bot token (required if modules.slack = true)
# MX_SLACK_TOKEN=

# 32-character encryption key for storing sensitive channel credentials
MX_ENCRYPTION_KEY={{ENCRYPTION_KEY}}
`

export async function runInit(options: InitOptions): Promise<void> {
  console.log('')
  p.intro(chalk.bold('WatchDeck Setup Wizard'))

  const existing = checkExistingFiles()
  const hasExisting = existing.config || existing.env

  // Overwrite check
  if (hasExisting && !options.force) {
    const files = [existing.config && CONFIG_FILE, existing.env && ENV_FILE]
      .filter(Boolean)
      .join(' and ')

    const overwrite = await p.confirm({
      message: `${chalk.yellow(files)} already exist. Overwrite?`,
      initialValue: false,
    })

    if (p.isCancel(overwrite) || !overwrite) {
      p.cancel('Setup cancelled. Use --force to skip this prompt.')
      process.exit(0)
    }
  }

  // Default mode — skip wizard
  if (options.defaults) {
    writeFiles({
      port: '4000',
      dbUri: 'mongodb://localhost:27017/watchdeck',
      dbName: 'watchdeck',
      dbPrefix: 'mx_',
      dashboardMode: 'standalone',
      discord: 'false',
      slack: 'false',
      encryptionKey: generateEncryptionKey(),
    })

    p.outro(chalk.green('Config generated with defaults. Edit watchdeck.config.js to customise.'))
    return
  }

  // Step 1 — Port
  const port = await p.text({
    message: 'Which port should WatchDeck run on?',
    placeholder: '4000',
    defaultValue: '4000',
    validate: (value) => {
      if (!value) return // empty = accept default
      const n = Number(value)
      if (isNaN(n) || n < 1 || n > 65535) return 'Enter a valid port number (1-65535)'
    },
  })
  if (p.isCancel(port)) { p.cancel('Setup cancelled.'); process.exit(0) }

  // Step 2 — MongoDB location
  const dbUri = await p.text({
    message: 'MongoDB connection URI',
    placeholder: 'mongodb://localhost:27017/watchdeck',
    defaultValue: 'mongodb://localhost:27017/watchdeck',
    validate: (value) => {
      if (!value) return // empty = accept default
      if (!value.startsWith('mongodb://') && !value.startsWith('mongodb+srv://')) {
        return 'URI must start with mongodb:// or mongodb+srv://'
      }
    },
  })
  if (p.isCancel(dbUri)) { p.cancel('Setup cancelled.'); process.exit(0) }

  // Step 3 — DB name
  const dbName = await p.text({
    message: 'Database name',
    placeholder: 'watchdeck',
    defaultValue: 'watchdeck',
    validate: (value) => {
      if (!value) return // empty = accept default
      if (!value.trim()) return 'Database name cannot be empty'
    },
  })
  if (p.isCancel(dbName)) { p.cancel('Setup cancelled.'); process.exit(0) }

  // Step 4 — Collection prefix
  const dbPrefix = await p.text({
    message: 'Collection prefix',
    placeholder: 'mx_',
    defaultValue: 'mx_',
    validate: (value) => {
      if (!value) return // empty = accept default
      if (!/^[a-z][a-z0-9_]*_$/.test(value)) {
        return 'Prefix must be lowercase letters/numbers, ending with underscore (e.g. mx_)'
      }
    },
  })
  if (p.isCancel(dbPrefix)) { p.cancel('Setup cancelled.'); process.exit(0) }

  // Step 5 — Dashboard mode
  const dashboardMode = await p.select({
    message: 'Dashboard mode',
    options: [
      { value: 'standalone', label: 'Standalone', hint: 'WatchDeck serves the dashboard itself' },
      { value: 'mounted', label: 'Mounted', hint: 'Import the React component into your own app' },
    ],
  })
  if (p.isCancel(dashboardMode)) { p.cancel('Setup cancelled.'); process.exit(0) }

  // Step 6 — Notification channels
  const channels = await p.multiselect({
    message: 'Which notification channels do you want to enable?',
    options: [
      { value: 'discord', label: 'Discord' },
      { value: 'slack', label: 'Slack' },
    ],
    required: false,
  })
  if (p.isCancel(channels)) { p.cancel('Setup cancelled.'); process.exit(0) }

  writeFiles({
    port: port as string,
    dbUri: dbUri as string,
    dbName: dbName as string,
    dbPrefix: dbPrefix as string,
    dashboardMode: dashboardMode as string,
    discord: (channels as string[]).includes('discord') ? 'true' : 'false',
    slack: (channels as string[]).includes('slack') ? 'true' : 'false',
    encryptionKey: generateEncryptionKey(),
  })

  p.outro(
    chalk.green('Setup complete!') +
      `\n\n  Run ${chalk.cyan('watchdeck start')} to launch the server.\n`,
  )
}

interface TemplateVars {
  port: string
  dbUri: string
  dbName: string
  dbPrefix: string
  dashboardMode: string
  discord: string
  slack: string
  encryptionKey: string
}

function writeFiles(vars: TemplateVars): void {
  const dbUriWithName = vars.dbUri.replace(/\/[^/]*$/, `/${vars.dbName}`)

  const configContent = renderTemplate(CONFIG_TEMPLATE, {
    PORT: vars.port,
    DASHBOARD_MODE: vars.dashboardMode,
    DISCORD: vars.discord,
    SLACK: vars.slack,
  })

  const envContent = renderTemplate(ENV_TEMPLATE, {
    DB_URI: dbUriWithName,
    DB_PREFIX: vars.dbPrefix,
    ENCRYPTION_KEY: vars.encryptionKey,
  })

  fs.writeFileSync(path.resolve(process.cwd(), CONFIG_FILE), configContent, 'utf8')
  fs.writeFileSync(path.resolve(process.cwd(), ENV_FILE), envContent, 'utf8')
}
